### ISSUE TITLE
Ingenieria de requerimientos

### ISSUE THREAD

**Issue by Arnold-Js** [SistemasTecTlaxiaco/actividad-1-mapa-mental-Arnold-Js#1]
[mapa mental-Ingenieria de requerimientos.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-mapa-mental-Arnold-Js/files/10772072/mapa.mental-Ingenieria.de.requerimientos.pdf)

**Comment by Aricel117** [comment]
Calif: 18
Ben hecho

**Comment by josealfredo79** [comment]
Bien hecho..
